dist: bionic
language: ruby

before_install:
  - gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)
  - gem update bundler --conservative
  - sudo apt-get update 1>/dev/null 
  - sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev ruby-bundler bsdtar libz-dev libxml2-dev bats fping 1>/dev/null

# Cache the big Vagrant boxes
cache:
  directories:
  - /home/travis/.vagrant.d/boxes

install:
  - sudo bundle install
  - sudo bundle --binstubs /tmp/exec 1>/dev/null

notifications:
  email: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
    - 2.5.7

matrix:
  include:
    - env: VAGRANT_VERSION=master
      rvm: 2.5.7
    - env: VAGRANT_VERSION=v2.2.4
      rvm: 2.5.7
    - env: VAGRANT_VERSION=v2.1.5
      rvm: 2.5.7
    - env: VAGRANT_VERSION=v2.0.4
      rvm: 2.5.7

# execue tests via BATS
script:
- sudo /tmp/exec/vagrant --version
- bundle exec rspec --color --format documentation

# downloading the debian box may take longer
# than 10 minutes, execute tests via travis_wait
- travis_wait 20 sudo bats tests/runtests.bats
